name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - dev
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use the version of Node.js your project requires

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm run build

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install -g firebase-tools

          # Deploy based on branch
          if [ "${{ github.ref }}" == "refs/heads/prod" ]; then
            firebase use --add prod
            firebase deploy --only hosting:prod
          elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            firebase use --add dev
            firebase deploy --only hosting:dev
          fi
